### Змінні оточення
@baseUrl = http://localhost:8080
@username = admin
@password = password

### Отримати JWT токен
POST {{baseUrl}}/api/auth/token?username={{username}}&password={{password}}

### Перевірити JWT токен (спочатку скопіюйте токен з відповіді попереднього запиту)
POST {{baseUrl}}/api/auth/validate
Content-Type: application/x-www-form-urlencoded

token=ваш_токен_тут&username={{username}}

### Отримати всі піци (Basic Auth)
GET {{baseUrl}}/api/pizzas
Authorization: Basic {{username}} {{password}}

### Отримати всі піци (JWT Auth - замініть токен на той, що отримали)
GET {{baseUrl}}/api/pizzas
Authorization: Bearer ваш_токен_тут

### Отримати піцу за ID
GET {{baseUrl}}/api/pizzas/1
Authorization: Basic {{username}} {{password}}

### Додати нову піцу
POST {{baseUrl}}/api/pizzas
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "name": "Маргарита",
    "size": "MEDIUM",
    "toppings": ["Сир", "Томати", "Базилік"],
    "price": 199.99
}

### Додати спеціальну піцу
POST {{baseUrl}}/api/pizzas/special
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "name": "Трюфельна Піца",
    "size": "LARGE",
    "toppings": ["Трюфелі", "Пармезан", "Рукола", "Оливкова олія"],
    "price": 499.99,
    "isSpecial": true
}

### Оновити піцу
PUT {{baseUrl}}/api/pizzas/1
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "name": "Маргарита Оновлена",
    "size": "LARGE",
    "toppings": ["Сир", "Томати", "Базилік", "Оливкова олія"],
    "price": 249.99
}

### Оновити рейтинг піци
PUT {{baseUrl}}/api/pizzas/1/rating
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
    "rating": 5
}

### Видалити піцу
DELETE {{baseUrl}}/api/pizzas/1
Authorization: Basic {{username}} {{password}}

### Знайти піци за розміром
GET {{baseUrl}}/api/pizzas/size/LARGE
Authorization: Basic {{username}} {{password}}

### Знайти піци за ціною
GET {{baseUrl}}/api/pizzas/price?maxPrice=200
Authorization: Basic {{username}} {{password}}

### Приклади використання JWT токена (замініть токен на отриманий):

### Додати спеціальну піцу з JWT
POST {{baseUrl}}/api/pizzas/special
Authorization: Bearer ваш_токен_тут
Content-Type: application/json

{
    "name": "Преміум Піца",
    "size": "LARGE",
    "toppings": ["Лобстер", "Чорний трюфель", "Золоті пластівці"],
    "price": 999.99,
    "isSpecial": true
}

### Оновити рейтинг піци з JWT
PUT {{baseUrl}}/api/pizzas/2/rating
Authorization: Bearer ваш_токен_тут
Content-Type: application/json

{
    "rating": 4
}

### Отримання JWT токена
POST http://localhost:8080/api/auth/token?username=user&password=user
Content-Type: application/json

### Отримання JWT токена для адміна
POST http://localhost:8080/api/auth/token?username=admin&password=admin
Content-Type: application/json

### Отримання JWT токена для суперадміна
POST http://localhost:8080/api/auth/token?username=superadmin&password=superadmin
Content-Type: application/json

### Отримання всіх піц (доступно для всіх ролей)
GET http://localhost:8080/api/pizzas
Authorization: Bearer ваш_токен

### Отримання піци за ID (доступно для всіх ролей)
GET http://localhost:8080/api/pizzas/1
Authorization: Bearer ваш_токен

### Додавання нової піци (доступно для всіх ролей)
POST http://localhost:8080/api/pizzas
Authorization: Bearer ваш_токен
Content-Type: application/json

{
    "name": "Margherita",
    "size": "Medium",
    "toppings": ["Tomato Sauce", "Mozzarella", "Basil"],
    "price": 199.99
}

### Оновлення піци (доступно для всіх ролей)
PUT http://localhost:8080/api/pizzas/1
Authorization: Bearer ваш_токен
Content-Type: application/json

{
    "name": "Margherita",
    "size": "Large",
    "toppings": ["Tomato Sauce", "Mozzarella", "Basil"],
    "price": 249.99
}

### Видалення піци (доступно для всіх ролей)
DELETE http://localhost:8080/api/pizzas/1
Authorization: Bearer ваш_токен

### Пошук піц за розміром (доступно для всіх ролей)
GET http://localhost:8080/api/pizzas/size/Medium
Authorization: Bearer ваш_токен

### Пошук піц за ціною (доступно для всіх ролей)
GET http://localhost:8080/api/pizzas/price?maxPrice=200
Authorization: Bearer ваш_токен

### Додавання спеціальної піци (тільки для адміна)
POST http://localhost:8080/api/pizzas/admin/special
Authorization: Bearer ваш_токен
Content-Type: application/json

{
    "name": "Special Margherita",
    "size": "Large",
    "toppings": ["Tomato Sauce", "Mozzarella", "Basil", "Extra Cheese"],
    "price": 299.99
}

### Оновлення рейтингу піци (тільки для адміна)
PUT http://localhost:8080/api/pizzas/admin/1/rating?rating=5
Authorization: Bearer ваш_токен 